/* Autogenerated by png2wx.pl on Sun Jan 18 18:39:20 2015 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_ga_anchor_cyan_25;
extern wxBitmap *_img_ga_anchor_cyan_30;
extern wxBitmap *_img_ga_toolbar;

#endif /* ICONS_H */
