/* Autogenerated by png2wx.pl on Thu Jan 22 10:44:24 2015 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_ga_anchor;
extern wxBitmap *_img_ga_toolbar;
extern wxBitmap *_img_ga_toolbar_on;

#endif /* ICONS_H */
